events/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('page_<int:page>', views.events, name='events'),
    path('<slug:event_id>', views.event_detail, name='event_detail'),
    path('add_event/', views.add_event, name='add_event'),
    path('edit_event/<slug:event_id>/', views.edit_event, name='edit_event'),
    path('delete_event/<slug:event_id>/', views.delete_event,
         name='delete_event'),
]

star_seekers/urls.py
from django.contrib import admin
from django.urls import path, include
from events.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('events/', include('events.urls')),
    path('accounts/', include('allauth.urls')),
]

handler404 = 'events.views.handler404'
handler500 = 'events.views.handler500'
handler403 = 'events.views.handler403'
handler405 = 'events.views.handler405'

events/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

# options for event expected_weather field
WEATHER_OPTIONS = ((0, 'Unknown'), (1, 'Clear'), (2, 'Chilly'), (3, 'Rainy'),
                   (4, 'Snowy'), (5, 'Stormy'))
# options for guide roles field
GUIDE_ROLES = ((0, 'Junior Seeker'), (1, 'Senior Seeker'), (3, 'Guest Seeker'))


class Guide(models.Model):
    """
    Guide model - represents a small profile of an event host.

    Instances of this model are ordered alphabetically by name.
    """

    name = models.CharField(max_length=50)
    role = models.IntegerField(choices=GUIDE_ROLES, default=0)
    image = CloudinaryField('image', default='placeholder')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Event(models.Model):
    """
    Event model - represents a single star seeking event.

    Instances of this model are ordered by start date and time,
    the nearest events appear first.
    """

    title = models.CharField(max_length=50, unique=True)
    description = models.TextField(max_length=600)
    image = CloudinaryField('image', default='placeholder')
    event_date = models.DateField()
    start_time = models.TimeField()
    meet_point = models.CharField(max_length=100)
    expected_weather = models.IntegerField(choices=WEATHER_OPTIONS, default=0)
    guide = models.ForeignKey(Guide, on_delete=models.RESTRICT,
                              related_name='events')

    class Meta:
        ordering = ['event_date', 'start_time']

    def __str__(self):
        return self.title


class Question(models.Model):
    """
    Question model - represents a single user question about an event.

    Instances of this model are ordered by upload time, first asked questions
    appear first.
    """

    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='question')
    event = models.ForeignKey(Event, on_delete=models.CASCADE,
                              related_name='question')
    question_title = models.CharField(max_length=100)
    question_details = models.TextField(max_length=600)
    uploaded_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['uploaded_on']

    def __str__(self):
        return f'Question about {self.event}: {self.question_title}'


class Answer(models.Model):
    """
    Answer model - represents an admin's answer to a single Question.

    Instances of this model are ordered by their relevant questions.
    """

    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='answer')
    question = models.OneToOneField(Question, on_delete=models.CASCADE,
                                    related_name='answer')
    content = models.TextField(max_length=600)
    answered_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['question']

    def __str__(self):
        return f'Answer for Question: {self.question.question_title}'

events/forms.py
from django import forms
from .models import Event, Question


class EventForm(forms.ModelForm):
    """
    Form used to add and/or edit events from frontend
    """

    class Meta:
        model = Event
        fields = ('title', 'description', 'image', 'event_date', 'start_time',
                  'meet_point', 'expected_weather', 'guide')


class QuestionForm(forms.ModelForm):
    """
    Form used to upload questions about events from frontend
    """

    class Meta:
        model = Question
        fields = ('question_title', 'question_details')

events/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.admin.views.decorators import staff_member_required
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage
from .models import Guide, Event, Question, Answer
from .forms import EventForm, QuestionForm


def index(request):
    """
    Renders home page using index.html.

    Passes 'Home' as the page title in context.
    """

    template = 'index.html'

    context = {
        'page_title': 'Home'
    }

    return render(request, template, context)


def events(request, page=1):
    """
    Renders events page using events.html.

    Passes upcoming events as 'events' and 'Events' as the page title
    in context.
    Uses Paginator to return 6 events per page.
    """

    today = timezone.now()
    upcoming_events = Event.objects.filter(event_date__gte=today)
    paginator = Paginator(upcoming_events, 6)

    try:
        upcoming_events = paginator.page(page)
    except EmptyPage:
        upcoming_events = paginator.page(paginator.num_pages)

    template = 'events.html'
    context = {
        'events': upcoming_events,
        'page_title': 'Events'
    }

    return render(request, template, context)


def event_detail(request, event_id):
    """
    Renders event details page using event_detail.html.

    Passes to context:
    - question form from forms.py as 'question_form'
    - relevant event as 'event'
    - questions about the event (if any) as 'asked_questions'
    - relevant question answers (if any) as 'answers'
    - the event's title as the page title.

    If a post request is made from a user submitting a question
    then the view receives the form data and adds the author and event
    info to the question before saving it to the db and redirecting the user
    back to the same page.
    """

    event = get_object_or_404(Event, id=event_id)
    event_questions = Question.objects.filter(event=event)

    answers = []
    if event_questions:
        for question in event_questions:

            answer = Answer.objects.filter(question=question)

            if answer:
                answers.append(answer[0])

    template = 'event_detail.html'
    question_form = QuestionForm()

    if request.method == 'POST' and request.user.is_authenticated:
        question_form = QuestionForm(request.POST)

        if question_form.is_valid():
            question = question_form.save(commit=False)
            question.author = request.user
            question.event = event
            question.save()

            return redirect(
                reverse('event_detail', kwargs={'event_id': event.id})
            )

    context = {
        'question_form': question_form,
        'event': event,
        'asked_questions': event_questions,
        'answers': answers,
        'page_title': f'{event.title}',
    }

    return render(request, template, context)


@staff_member_required
def add_event(request):
    """
    Renders add event form using event_form.html. Only accessible to admins.

    Passes to context:
    - The empty event form from forms.py as 'event_form'
    - 'Add Event' as the submit button text
    - 'New Event' as the page title.

    If a post request is made from the user attempting to create an event
    then the view receives and validates the form data before saving it to
    the db as a new Event instance. The user is redirected to the new event's
    detail page.
    """

    template = 'event_form.html'
    event_form = EventForm()

    if request.method == 'POST':
        event_form = EventForm(request.POST, request.FILES)

        if event_form.is_valid():
            event = event_form.save()

            return redirect(
                reverse('event_detail', kwargs={'event_id': event.id})
            )

    context = {
        'event_form': event_form,
        'submit_button_text': 'Add Event',
        'page_title': 'New Event'
    }

    return render(request, template, context)


@staff_member_required
def edit_event(request, event_id):
    """
    Renders edit event from using event_form.html. Only accessible to admins.

    Passes to context:
    - The pre-filled event form using event info as 'event_form'
    - 'Save Changes' as the submit button text
    - 'Editing Event: (relevant event title)' as the page title

    If a post request is made from the user attempting to save their event
    changes then the view receives and validates the form data before updating
    the existing event info. The user is redirected to the changed event's
    detail page.
    """

    template = 'event_form.html'

    event = get_object_or_404(Event, id=event_id)
    event_form = EventForm(instance=event)

    if request.method == 'POST':
        event_form = EventForm(request.POST, request.FILES, instance=event)

        if event_form.is_valid():
            updated_event = event_form.save()

            return redirect(
                reverse('event_detail', kwargs={'event_id': updated_event.id})
            )

    context = {
        'event_form': event_form,
        'submit_button_text': 'Save Changes',
        'page_title': f'Editing Event: {event.title}'
    }

    return render(request, template, context)


@staff_member_required
def delete_event(request, event_id):
    """
    Deletes the event associated with the request. Only accessible to admins.

    Redirects user to the home page.
    """
    event = get_object_or_404(Event, id=event_id)
    event.delete()

    return redirect(reverse('home'))


def handler403(request, exception):
    """
    Render custom 403 template instead of default.
    """

    return render(request, '403.html', status=403)


def handler404(request, exception):
    """
    Render custom 404 template instead of default.
    """

    return render(request, '404.html', status=404)


def handler405(request, exception):
    """
    Render custom 405 template instead of default.
    """

    return render(request, '405.html', status=405)


def handler500(request):
    """
    Render custom 500 template instead of default.
    """

    return render(request, '500.html', status=500)

templates/405.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <div class="col s12 center">
        <h2><i class="material-icons">error</i> 405 - Method Not Allowed</h2>
        <p>Sorry, something seems to have gone wrong!</p>
        <hr>
        <p>Let's get you home... <a href="{% url 'home' %}" class="btn">Return Home</a></p>
    </div>
</div>

{% endblock %}

templates/add_event.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
    {{ event_form }}
    {% csrf_token %}
    <button type="submit">Add Event</button>
</form>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Star Seekers is a social group of lovers of the night sky.">
    <meta name="keywords" content="stars, moon, night, sky, dark, late, event, events, local events">
    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <!-- materialize css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- materialize icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- font awesome icons -->
    <script src="https://kit.fontawesome.com/b327c6348f.js" crossorigin="anonymous"></script>
    <!-- css link -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- emailJS init -->
    <script src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js"></script>
    <script>
        (function() {
            emailjs.init('iyvtwzisVm1I-q4ie');
        })();
    </script>

    <!-- page title, uses passed in values from context to customise for each page -->
    <title>Star Seekers | {{ page_title }}</title>
</head>
<body>
    <header>
        <!-- Navigation bar -->
        <nav>
            <div class="nav-wrapper blue darken-4">
                <div class=restrict-max-width>
                    <a href="{% url 'home' %}" class="brand-logo amber-text text-lighten-3">Star Seekers</a>
                    <a href="#" data-target="mobile-demo" class="sidenav-trigger amber-text text-lighten-3 right"><i class="material-icons">menu</i></a>
                    <ul id="nav-mobile" class="right hide-on-med-and-down">
                        <li><a href="{% url 'home' %}" class="amber-text text-lighten-3">Home</a></li>
                        <li><a href="{% url 'events' 1 %}" class="amber-text text-lighten-3">Events</a></li>
                        <!-- If user is already signed in, show sign-out link. If not, show sign-in link-->
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'account_logout' %}" class="amber-text text-lighten-3">Sign Out</a></li>
                        {% else %}
                        <li><a href="{% url 'account_login' %}" class="amber-text text-lighten-3">Sign In/Register</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <!-- navbar hamburger menu for smaller screens -->
        <ul class="sidenav blue darken-4" id="mobile-demo">
            <li><a href="{% url 'home' %}" class="amber-text text-lighten-3">Home</a></li>
            <li><a href="{% url 'events' 1 %}" class="amber-text text-lighten-3">Events</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'account_logout' %}" class="amber-text text-lighten-3">Sign Out</a></li>
            {% else %}
            <li><a href="{% url 'account_login' %}" class="amber-text text-lighten-3">Sign In/Register</a></li>
            {% endif %}
        </ul>
    </header>

    <!-- Main content -->
    <main>
        <div class="container">
            {% block content %}
            <!-- Extended content goes here -->
            {% endblock content %}
        </div>
    </main>

    <!-- Footer -->
    <footer class="page-footer blue darken-4">
        <div class="container">
            <p class="footer-text">Check us out on our socials:</p>
            <div class="footer-links">
                <!-- social links -->
                <a href="https://facebook.com/" target="_blank" aria-label="Link to Facebook"><i class="fa-brands fa-facebook"></i></a>
                <a href="https://twitter.com/" target="_blank" aria-label="Link to Twitter"><i class="fa-brands fa-twitter"></i></a>
                <a href="https://instagram.com/" target="_blank" aria-label="Link to Instagram"><i class="fa-brands fa-instagram"></i></a>
                <a href="https://tiktok.com/" target="_blank" aria-label="Link to TikTok"><i class="fa-brands fa-tiktok"></i></a>
            </div>
        </div>
        <div class="footer-copyright restrict-max-width">
            © 2023 Star Seekers
        </div>
    </footer>

    <!-- materialize js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- js link -->
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/event_detail.html
{% extends 'base.html' %}

{% block content %}

<!-- row for event details, guide details, and booking form -->
<div class="row">
    <!-- event image column -->
    <div class="col s12 m12 l6">
        {% if 'placeholder' in event.image.url %}
        <img src="https://images.pexels.com/photos/746111/pexels-photo-746111.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Dark blue midnight sky with central glowing full moon." class="details-event-image">
        {% else %}
        <img src="{{ event.image.url }}" alt="Picture of the sky at event location" class="details-event-image">
        {% endif %}
    </div>
    <!-- event details column -->
    <div class="col s12 m8 l6" id="event-details">
        <h2 id="event-title">{{ event.title }}</h2>
        <p>{{ event.description }}</p>
        <p>Date & Time: {{ event.event_date }} | <span id="event-time">{{ event.start_time }}</span></p>
        <p>Meet Point: <span id="event-meet-point">{{ event.meet_point }}</span></p>
        <p>Expected Weather: {{ event.get_expected_weather_display }}</p>
    </div>

    <!-- guide details column -->
    <div class="col s12 m4 l4 center">
        <h3>Event Guide</h3>
        {% if 'placeholder' in event.guide.image.url %}
        <img src="https://images.pexels.com/photos/1136575/pexels-photo-1136575.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Unknown guide against night sky" class="details-guide-image">
        {% else %}
        <img src="{{ event.guide.image.url }}" alt="Picture of this event's guide" class="details-guide-image">
        {% endif %}
        <p>{{ event.guide.name }} | {{ event.guide.get_role_display }}</p>
    </div>

    <!-- booking column -->
    <div class="col s12 m10 l8 push-m1">
        <h3>Want to come along?</h3>
        {% if user.is_authenticated %}
        <!-- if user is authenticated, form is displayed -->
        <form id="booking-form" action="#!">
            <!-- name imput -->
            <label for="booking-name">Name</label>
            <input type="text" id="booking-name" name="name" placeholder="Full name" required>

            <!-- email input -->
            <label for="booking-email">Email Address</label>
            <input type="email" id="booking-email" name="email" placeholder="example123@email.com" required>

            <!-- group size input -->
            <label for="booking-group-size">Group Size</label>
            <select name="group-size" id="booking-group-size">
                <option value="1" selected>1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
            </select>

            <!-- hidden inputs for emailJS values -->
            <input type="hidden" name="event_title">
            <input type="hidden" name="event_meet_point">
            <input type="hidden" name="event_start_time">

            <button type="submit" value="submit" class="details-button">Book Now</button>
        </form>
        {% else %}
        <!-- if user is not authenticated, they are shown this instead -->
        <p>Please Sign In or Create an Account to book a place at this event.</p>
        {% endif %}
    </div>

    <!-- booking submission modal, displayed on form submit -->
    <div id="booking-modal" class="modal">
        <div class="modal-content">
            <h4>You're all booked up!</h4>
            <p>Check your email for your booking confirmation, all you have to do now is contain your excitement!</p>
            <p>We can't wait to see you soon.</p>
        </div>
        <div class="modal-footer">
            <a href="{% url 'events' 1 %}" class="modal-close waves-effect waves-green btn-flat">Return to Events</a>
        </div>
    </div>
</div>

<hr>

<!-- row for ask Q form and previous Q display -->
<div class="row">
    <!-- question form column -->
    <div class="col s12 m12 l12">
        <h3>Ask a Question</h3>
        {% if user.is_authenticated %}
        <!-- if user is authenticated, question form is displayed -->
        <form method="POST">
            {{ question_form.as_p }}
            {% csrf_token %}
            <button type="submit" class="details-button">Submit Question</button>
        </form>
        {% else %}
        <!-- if user is not authenticated, this message is shown instead -->
        <p>Please Sign In or Create an Account to ask questions about this event.</p>
        {% endif %}
    </div>

    <!-- previous questions column -->
    <div class="col s12 m12 l12">
        <h3>Previously Asked Questions</h3>
        <!-- if any questions are asked, iterate through them and display them as shown below. -->
        {% if asked_questions %}
        {% for question in asked_questions %}
        <div class="row asked-questions">
            <!-- asked question column -->
            <div class="col s12 m6 l6">
                <div class="question">
                    <p class="question-title">{{ question.question_title }}</p>
                    <p>{{ question.question_details }}</p>
                    <p class="right">Asked by {{ question.author }} on {{ question.uploaded_on }}</p>
                </div>
            </div>
            <!-- answer column -->
            <div class="col s12 m6 l6">
                <div class="answer">
                    <!-- from the received list of answers, if any belong to the current question: display the answer here -->
                    {% for answer in answers %}
                    {% if answer.question == question %}
                    <p>{{ answer.content }}</p>
                    <p class="right">Answered by {{ answer.author }} on {{ answer.answered_on }}</p>
                    {% endif %}
                    {% endfor %}
                    <!-- if no answers belong to the question, javscript handles displaying the default 'no answer' text. -->
                    <!-- this is because jinja2 does not support breaking loops by default. -->
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <!-- if the event has no asked questions, show this message instead -->
        <div class="row">
            <div class="col s12 m12 l12 center">
                <p>No one has asked any questions about this event yet.</p>
            </div>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/event_details.html
{% extends 'base.html' %}

{% block content %}

<!-- event details -->
<div class="event-details">

</div>

<!-- guide details -->
<div class="guide-details">

</div>

<!-- booking form -->
<div class="booking">
    <form action="" method="POST">
        {{ event.title }}
        form goes here
    </form>
</div>

{% endblock %}

templates/event_form.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" enctype="multipart/form-data">
    {{ event_form.as_p }}
    {% csrf_token %}
    <button type="submit">{{ submit_button_text }}</button>
</form>

{% endblock %}

templates/events.html
{% extends 'base.html' %}

{% block content %}

<!-- page title and add event button container-->
<div>
    <h3 id="events-page-title">Upcoming Events</h3>
    <!-- only show admins the add event option -->
    {% if user.is_staff %}
    <a href="{% url 'add_event' %}" class="right button add-button"><i class="material-icons">add_circle_outline</i></a>
    {% endif %}
</div>

<hr>

<!-- upcoming events display -->
<div class="event-list">
    <div class="row">
        {% for event in events %}
        <div class="col s12 m6 l4">
            <div class="event-card">
                <a href="{% url 'event_detail' event.id %}">
                    <!-- if no image is assigned currently selected as the event_image, show this default instead -->
                    {% if 'placeholder' in event.image.url %}
                    <img src="https://images.pexels.com/photos/746111/pexels-photo-746111.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Dark blue midnight sky with central glowing full moon." class="event-card-image">
                    {% else %}
                    <img src="{{ event.image.url }}" alt="Starry sky" class="event-card-image">
                    {% endif %}
                    <hr class="event-card-divider">
                    <p class="event-card-title">{{ event.title }}</p>
                    <p class="event-card-date-and-time">{{ event.event_date }} | {{ event.start_time }}</p>
                </a>
                
                <!-- only show admins the edit and delete event options -->
                {% if user.is_staff %}
                <a href="{% url 'edit_event' event.id %}" class="button edit-button"><i class="material-icons">create</i></a>
                <button data-target="delete-modal-{{ event.id }}" class="button delete-button modal-trigger"><i class="material-icons">close</i></button>
                
                <!-- delete confirmation modal -->
                <div id="delete-modal-{{ event.id }}" class="modal">
                    <div class="modal-content">
                        <h4>Important!</h4>
                        <p>Are you sure you want to delete this event: {{ event.title }}</p>
                        <p>This action cannot be undone.</p>
                    </div>
                    <div class="modal-footer">
                        <a href="{% url 'delete_event' event.id %}" class="waves-effect btn-flat">Delete event</a>
                        <a href="#" class="modal-close waves-effect btn-flat">Cancel</a>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- pagination controls -->
    <div class="row">
        <div class="col s12 m10 l8 center push-m1 push-l2">
            <ul class="pagination">
                
                <!-- if there is a previous page before the current one, allow the chevron to link to the previous page -->
                {% if events.has_previous %}
                <li><a href="{% url 'events' events.previous_page_number %}"><i class="material-icons">chevron_left</i></a></li>
                {% else %}
                <li class="disabled"><a><i class="material-icons">chevron_left</i></a></li>
                {% endif %}

                <li>
                    Page {{ events.number }} of {{ events.paginator.num_pages }}
                </li>

                <!-- if there is a next page after the current one, allow the chevron to link to the next page -->
                {% if events.has_next %}
                <li><a href="{% url 'events' events.next_page_number %}"><i class="material-icons">chevron_right</i></a></li>
                {% else %}
                <li class="disabled"><a><i class="material-icons">chevron_right</i></a></li>
                {% endif %}

              </ul>
        </div>
    </div>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

<!-- Landing page image -->
<div class="jumbotron"></div>

<!-- title and about us section -->
<div class="row main-title-background">
    <div class="col s12 m10 l8 push-m1 push-l2">
        <h1 id="main-title">Star Seekers</h1>
    </div>
</div>

<!-- about title row -->
<div class="row">
    <div class="col s12 m8 push-m2">
        <h2 id="about-title">Come and seek the stars with us...</h2>
    </div>
</div>

<!-- about us content row -->
<div class="row about-row">
    <!-- about column 1 -->
    <div class="col s12 m12 l4 center">
        <i class="fa-solid fa-star about-icon"></i>
        <p>
            Modern life is structured around daylight. We work in the daytime and sleep at night. 
            Here at Star Seekers, we think that should change. As beautiful as the world can be 
            when it is lit up by the sun, we think the true beauty of our planet is unveiled 
            under the stars. We want you to see that beauty too, that is what Star Seekers is all about.
        </p>
    </div>
    <!-- about column 2 -->
    <div class="col s12 m12 l4 center">
        <i class="fa-solid fa-sun about-icon"></i>
        <p>
            Our team of incredible guides host night-time events at various times and locations with 
            all sorts of different themes for you to choose from. Our events are usually an hour in 
            length and involve: meeting your fellow seekers for the night, taking a short tour of the
            night's location, and finally stopping and truly embracing the sky at the event's star-stop!
        </p>
    </div>
    <!-- about column 3 -->
    <div class="col s12 m12 l4 center">
        <i class="fa-solid fa-moon about-icon"></i>
        <p>
            To get started, check out the Events page to see a list of upcoming events. If
            any take your fancy, all you have to do is click on the event to view more details about it.
            From there you can ask a question and view questions asked by others. Most importantly,
            after creating an account you can book your place at any event you like. We can't wait to
            see you soon!
        </p>
    </div>
</div>
    
{% endblock %}